hubot-test:
  image: ${DOCKER_IMAGE_NAME}:latest
  container_name: hubot-groovenauts-test
  links:
    - redis
  environment:
    - TZ

redis:
  extends:
    file: docker-compose.yml
    service: redis

